### ISSUE TITLE
Primeira Sprint

### ISSUE THREAD

**Issue by John-Luke** [josetvictor/PDS-SystemPapi#1]
### Configuração
- [x] Organização de pastas (Resolvido em #2) 
- [x] Conexão com BD usando PDO (Resolvido em #3)

### Funcionalidades
- [x]  CRUD Produtos (Resolvido em #9)
- [x]  CRUD Clientes (Resolvido em #5 e #8)

### Páginas
- [x] Home em html puro (seguindo o protótipo acordado a seguir)
![Protótipo Inicial da Home Page](https://user-images.githubusercontent.com/15695983/43995623-c5ddd9dc-9d87-11e8-952d-396a9d70989e.jpeg)

### Outros
- [x] Utilitário para facilitar criação de CRUDs (Resolvido em #4)
- POO (Sim, Papaiz com certeza vai pedir isso e faz parte do projeto ser em POO)

**Comment by John-Luke** [comment]
A parte de **Outros** sempre será para dúvidas sobre o projeto.

**Comment by John-Luke** [comment]
Fechando devido a toda a Sprint ter sido completada (bugs dessa Sprint devem ser inseridos aqui)

**Comment by John-Luke** [comment]
Fechando devido a toda a Sprint ter sido completada (bugs dessa Sprint devem ser inseridos aqui)
