### ISSUE TITLE
Segunda Sprint

### ISSUE THREAD

**Issue by John-Luke** [josetvictor/PDS-SystemPapi#10]
### Funcionalidades
  - [x] CRUD Fornecedores (Resolvido em #12)
  - [x] CRUD Funcionários (Resolvido em #13)

### Front (@htmlucas) 
  - [x] Padronização de páginas (Resolvido em #11)
  - [ ] Seleção de linha ou exclusão dessa funcionalidade (Não foi feita)

### BD (@Dia-VBC) 
  - [ ] Modelagem do banco (Desnecessário)
  - [ ] Arquivo SQL para padronização (Fica para próxima Sprint)

**Comment by John-Luke** [comment]
### Bugs dessa sprint
  - Compatibilidade da coluna `telefone(s)`
  - Nomes inválidos em atributos
(Vou atualizar quando chegar em casa)
