### ISSUE TITLE
Quarta Sprint

### ISSUE THREAD

**Issue by John-Luke** [josetvictor/PDS-SystemPapi#21]
### Funcionalidades
 - [ ] Salário (#18 e #19)

### Correções
  - [x] Compra e Venda #17
  - [x] Trocar `includes` por `require_once` (#18)
  - [x] Problemas com nomes de colunas (#18)
  - [x] Problemas com nomes de tabelas (#18)
  - [x] Problemas com o método para pegar o id dos objetos (#18)

### Melhorias
  - [x] Componentizar Front end (#17)

**Comment by John-Luke** [comment]
*Problemas da Sprint (maior parte causada pelo rebase)*
 - Valor Total não existe no bd (precisa criar a trigger)
 - Concatenação inválida na hora de mostrar as informações extras
 - Tabela `compra_venda` deveria ser `compravenda`
 - Não ter isset em várias variáveis
 - Não existência de uma `,` em `compras-alterar.php`
 - Retornar o último id adicionado
 - Data vai para o banco de forma incorreta
 - Telefone é visto como data
 - Enviar motorista e técnico
 - Adicionar o id do salário ao retornar todos os salários de um funcionário
